/**
 * The mark and the wordmark.
 *
 * The mark is a map pin with a photograph inside its head — a hill and a sun, the glyph everything
 * uses for "image". One shape for the two things this app does: a picture, and where it goes. It
 * also echoes the markers already dropped on the map, so the icon and the interface agree.
 *
 * A first version hung a pin's point off a rounded rectangle instead, and read unmistakably as a
 * speech bubble: a rounded box with a tail is a tooltip everywhere else. A pin cannot be mistaken.
 *
 * Stroked rather than filled, because the interface it sits in is soft-edged and low-contrast and
 * a solid blob would be the heaviest thing on screen. `scripts/make-icons.mjs` draws the same
 * shapes filled, which is what a launcher needs at 48px.
 *
 * The wordmark leans on weight rather than colour: **Snap** at 700 against *mapper* at 400. Two
 * tones would have meant a second accent, and the palette allows one.
 *
 * Inline SVG rather than an `<img>`: it costs no request, inherits `currentColor` so it works in
 * both themes without a second asset, and stays sharp at any size. The icon files in
 * `public/icons` are the same drawing, filled, generated by `scripts/make-icons.mjs`.
 */

export function Mark({ size = 24 }: { readonly size?: number }) {
  return (
    <svg
      className="mark"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      focusable="false"
    >
      {/* The pin: a teardrop, tip down. */}
      <path d="M12 21.6c0 0-6.7-6.3-6.7-11.3a6.7 6.7 0 1 1 13.4 0c0 5-6.7 11.3-6.7 11.3z" />
      {/* A hill and a sun — the least a picture can be and still be a picture. */}
      <path d="M8.4 12.6 11.3 8.9 14.4 12.6" />
      <circle cx="14.8" cy="8.1" r="1.2" />
    </svg>
  );
}

/**
 * The mark beside the name.
 *
 * `hero` is the landing screen; `bar` is the application header, where it replaces a plain `<h1>`
 * and where it is hidden entirely on a phone — the row it sits on is needed for Undo, Redo and
 * the menu, and measurement said the name was the least useful thing on it.
 */
export function Wordmark({ variant = 'bar' }: { readonly variant?: 'bar' | 'hero' }) {
  const hero = variant === 'hero';

  return (
    <span className={`wordmark ${hero ? 'wordmark-hero' : 'wordmark-bar'}`}>
      <Mark size={hero ? 46 : 20} />
      <span className="wordmark-text">
        <b>Snap</b><span>mapper</span>
      </span>
    </span>
  );
}
